trigger:
- main  # or your target branch

pool:
  vmImage: 'ubuntu-latest'


variables:
  acrName: 'Dockerchiedo'  # ✅ change to your ACR name (not the full URL)
  acrLoginServer: 'youracrname.azurecr.io'
  imageName: 'DockerImage'
  imageTag: 'latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: '<chiedozie>'  # 🔁 must have access to RG 'chid'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to ACR..."
      az acr login --name ${{ variables.acrName }}


ACR_NAME=$(ACR_NAME)
IMAGE_NAME=businessmonitorapp:latest

# Login to Azure Container Registry
az acr login --name $ACR_NAME

# Build the Docker image
docker build -f _Sage_cloudops-hcm-fr-iac-edi-repo/build/docker/BusinessMonitoring/App/Dockerfile -t $ACR_NAME.azurecr.io/$IMAGE_NAME .

# Push the Docker image to ACR
docker push $ACR_NAME.azurecr.io/$IMAGE_NAME

# Output the image name
echo "##vso[task.setvariable variable=imageName]$ACR_NAME.azurecr.io/$IMAGE_NAME"
