trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'Dockerchiedo'
  imageName: 'myapp'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '<Your-Service-Connection-Name>'  # Replace with your actual service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)
      az acr build --registry $(acrName) --image $(imageName):latest .
    workingDirectory: $(Build.SourcesDirectory)
