trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'Dockerchiedo'
  imageName: 'myapp'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-chiedo'  # Replace with your actual service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name Dockerchiedo
      az acr build --registry Dockerchiedo --image $(imageName):latest .
    workingDirectory: $(Build.SourcesDirectory)
